"""PyYAML rendering engine with block scalar support for pdf2yaml."""

from __future__ import annotations
import yaml
from typing import Dict, Any
from .models import YamlDocument


class CleanYamlDumper(yaml.SafeDumper):
    """Custom YAML dumper to render multi-line strings cleanly using block scalars (|)."""

    def represent_scalar(self, tag, value, style=None):
        if "\n" in value:
            style = "|"
        return super().represent_scalar(tag, value, style=style)


def render_document_to_yaml(doc: YamlDocument) -> str:
    """Render a YamlDocument object into a clean YAML string."""
    doc_dict = doc.model_dump(exclude_none=True, exclude_defaults=True)
    
    yaml_text = yaml.dump(
        doc_dict,
        Dumper=CleanYamlDumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        indent=2,
    )
    
    # Prepend header comment
    header = "# Generated by pdf2yaml converter (AI-Optimized Structure)\n---\n"
    return header + yaml_text
