"""
SQLite FTS5 Database Builder for Quantitative Finance Knowledge Base
Indexes all parsed YAML research papers across category subfolders into a fast SQLite FTS5 database.
"""

import os
import re
import sqlite3
import yaml
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple


def normalize_paper_id(file_path: Path) -> str:
    """Derive a canonical paper_id from filename or arXiv ID."""
    stem = file_path.stem
    # Match arXiv pattern e.g., 2501.06032 or 0704.2259 or 1502.02083
    arxiv_match = re.match(r"^(\d{4}\.\d{4,5})", stem)
    if arxiv_match:
        return f"arXiv:{arxiv_match.group(1)}"
    return stem


def init_db(db_path: Path) -> sqlite3.Connection:
    """Initialize the SQLite database with normalized tables and FTS5 search index."""
    if db_path.exists():
        try:
            db_path.unlink()
        except Exception:
            pass

    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode = WAL;")
    conn.execute("PRAGMA synchronous = NORMAL;")

    cursor = conn.cursor()

    # Core metadata table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS papers (
        paper_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        authors TEXT,
        category TEXT NOT NULL,
        source_file TEXT NOT NULL,
        total_pages INTEGER,
        abstract TEXT
    );
    """)

    # Paper sections & text blocks
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS sections (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        paper_id TEXT NOT NULL,
        page_number INTEGER,
        section_title TEXT,
        content_text TEXT,
        FOREIGN KEY (paper_id) REFERENCES papers(paper_id) ON DELETE CASCADE
    );
    """)

    # Mathematical equations
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS equations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        paper_id TEXT NOT NULL,
        page_number INTEGER,
        latex_raw TEXT NOT NULL,
        description TEXT,
        section_title TEXT,
        FOREIGN KEY (paper_id) REFERENCES papers(paper_id) ON DELETE CASCADE
    );
    """)

    # Cross-paper citations
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS citations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        source_paper_id TEXT NOT NULL,
        target_paper_id TEXT,
        citation_text TEXT NOT NULL,
        FOREIGN KEY (source_paper_id) REFERENCES papers(paper_id) ON DELETE CASCADE
    );
    """)

    # Domain entities & aliases
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS entities (
        entity_id TEXT PRIMARY KEY,
        canonical_name TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        aliases_json TEXT
    );
    """)

    # FTS5 Full-Text Search Virtual Table
    cursor.execute("""
    CREATE VIRTUAL TABLE IF NOT EXISTS papers_fts USING fts5(
        paper_id UNINDEXED,
        title,
        authors,
        category,
        content_text,
        tokenize = 'unicode61'
    );
    """)

    conn.commit()
    return conn


try:
    from yaml import CSafeLoader as SafeLoader
except ImportError:
    from yaml import SafeLoader


def parse_yaml_paper(yaml_file: Path) -> Optional[Dict[str, Any]]:
    """Load and parse a paper YAML file generated by pdf2yaml."""
    try:
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.load(f, Loader=SafeLoader)
            if not isinstance(data, dict):
                return None
            return data
    except Exception as e:
        print(f"Warning: Failed to parse YAML file {yaml_file}: {e}")
        return None


def extract_paper_records(yaml_data: Dict[str, Any], file_path: Path) -> Tuple[Dict[str, Any], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Extract structured paper records from YAML data.
    Returns: (paper_record, section_records, equation_records, citation_records)
    """
    paper_id = normalize_paper_id(file_path)
    metadata = yaml_data.get("metadata", {})
    category = file_path.parent.name

    title = metadata.get("title", file_path.stem)
    authors_raw = metadata.get("authors", [])
    if isinstance(authors_raw, list):
        authors = ", ".join(str(a) for a in authors_raw)
    else:
        authors = str(authors_raw) if authors_raw else ""

    total_pages = metadata.get("total_pages", 0)
    source_file = metadata.get("source_file", str(file_path))

    pages = yaml_data.get("pages", [])
    abstract = ""
    sections = []
    equations = []
    citations = []

    for p in pages:
        page_num = p.get("page_number", 1)
        sec_list = p.get("sections", [])
        for sec in sec_list:
            sec_title = sec.get("title", "")
            paragraphs = sec.get("paragraphs", [])
            text_block = "\n".join(str(para) for para in paragraphs) if paragraphs else ""
            
            # Check tables / rows for text
            tables = sec.get("tables", [])
            table_texts = []
            for t in tables:
                headers = t.get("headers", [])
                rows = t.get("rows", [])
                if headers:
                    table_texts.append(" ".join(str(h) for h in headers))
                for r in rows:
                    if isinstance(r, list):
                        table_texts.append(" ".join(" ".join(str(cell) for cell in item) if isinstance(item, list) else str(item) for item in r))
            if table_texts:
                text_block += "\n" + "\n".join(table_texts)

            if not abstract and ("abstract" in sec_title.lower() or page_num == 1):
                if len(text_block) > 30:
                    abstract = text_block[:1000]

            sections.append({
                "paper_id": paper_id,
                "page_number": page_num,
                "section_title": sec_title,
                "content_text": text_block
            })

            # Check for LaTeX equations or formulas in paragraphs
            for para in paragraphs:
                if isinstance(para, str) and ("\\" in para or "=" in para) and len(para) < 200:
                    # Potential math formula
                    if any(sym in para for sym in ["\\frac", "\\sum", "\\alpha", "\\beta", "\\delta", "f(x)", "="]):
                        equations.append({
                            "paper_id": paper_id,
                            "page_number": page_num,
                            "latex_raw": para.strip(),
                            "description": f"Formula in {sec_title}",
                            "section_title": sec_title
                        })

            # Extract arXiv citations using regex
            found_cites = re.findall(r"(?:arXiv:|\b)(\d{4}\.\d{4,5})\b", text_block)
            for cite in found_cites:
                target_id = f"arXiv:{cite}"
                if target_id != paper_id:
                    citations.append({
                        "source_paper_id": paper_id,
                        "target_paper_id": target_id,
                        "citation_text": f"Mentioned arXiv:{cite} in {sec_title}"
                    })

    paper_record = {
        "paper_id": paper_id,
        "title": title,
        "authors": authors,
        "category": category,
        "source_file": source_file,
        "total_pages": total_pages,
        "abstract": abstract
    }

    return paper_record, sections, equations, citations


def index_parsed_directory(data_dir: Path, db_path: Path) -> Dict[str, int]:
    """Index all YAML files in data_dir into db_path SQLite database."""
    conn = init_db(db_path)
    cursor = conn.cursor()

    yaml_files = list(data_dir.rglob("*.yaml"))
    total_files = len(yaml_files)
    total_papers = 0
    total_sections = 0
    total_equations = 0
    total_citations = 0

    for idx, yaml_file in enumerate(yaml_files, 1):
        yaml_data = parse_yaml_paper(yaml_file)
        if not yaml_data:
            continue

        paper_rec, sections, equations, citations = extract_paper_records(yaml_data, yaml_file)

        # Insert paper record
        cursor.execute("""
        INSERT OR REPLACE INTO papers (paper_id, title, authors, category, source_file, total_pages, abstract)
        VALUES (?, ?, ?, ?, ?, ?, ?);
        """, (
            paper_rec["paper_id"],
            paper_rec["title"],
            paper_rec["authors"],
            paper_rec["category"],
            paper_rec["source_file"],
            paper_rec["total_pages"],
            paper_rec["abstract"]
        ))
        total_papers += 1

        # Combine text content for FTS5 index
        combined_text = []
        for sec in sections:
            cursor.execute("""
            INSERT INTO sections (paper_id, page_number, section_title, content_text)
            VALUES (?, ?, ?, ?);
            """, (sec["paper_id"], sec["page_number"], sec["section_title"], sec["content_text"]))
            total_sections += 1
            if sec["content_text"]:
                combined_text.append(f"{sec['section_title']}: {sec['content_text']}")

        for eq in equations:
            cursor.execute("""
            INSERT INTO equations (paper_id, page_number, latex_raw, description, section_title)
            VALUES (?, ?, ?, ?, ?);
            """, (eq["paper_id"], eq["page_number"], eq["latex_raw"], eq["description"], eq["section_title"]))
            total_equations += 1

        for cite in citations:
            cursor.execute("""
            INSERT INTO citations (source_paper_id, target_paper_id, citation_text)
            VALUES (?, ?, ?);
            """, (cite["source_paper_id"], cite["target_paper_id"], cite["citation_text"]))
            total_citations += 1

        # Insert into FTS5 index
        full_paper_text = "\n".join(combined_text)
        cursor.execute("""
        INSERT INTO papers_fts (paper_id, title, authors, category, content_text)
        VALUES (?, ?, ?, ?, ?);
        """, (paper_rec["paper_id"], paper_rec["title"], paper_rec["authors"], paper_rec["category"], full_paper_text))

        if idx % 100 == 0 or idx == total_files:
            conn.commit()
            print(f"  Processed {idx}/{total_files} papers...")

    conn.commit()
    conn.close()

    return {
        "papers": total_papers,
        "sections": total_sections,
        "equations": total_equations,
        "citations": total_citations
    }


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Build Quantitative Finance SQLite FTS5 Database")
    parser.add_argument("--data-dir", type=str, default="data/parsed", help="Path to parsed YAML directory")
    parser.add_argument("--db-path", type=str, default="second_brain.db", help="Target SQLite database path")
    args = parser.parse_args()

    data_path = Path(args.data_dir)
    db_path = Path(args.db_path)

    if not data_path.exists():
        print(f"Error: Data directory {data_path} does not exist.")
        return

    print(f"Indexing Quantitative Papers from {data_path} into {db_path}...")
    stats = index_parsed_directory(data_path, db_path)
    print("Indexing Complete!")
    print(f"  Papers Indexed:    {stats['papers']}")
    print(f"  Sections Indexed:  {stats['sections']}")
    print(f"  Equations Indexed: {stats['equations']}")
    print(f"  Citations Indexed: {stats['citations']}")


if __name__ == "__main__":
    main()
